Feature/edit card
gacsphere/capstone-project pull request #15
Opened 2022-10-24 18:19 UTC by gacsphere

The user can edit and save cards which will be appended to the cards list.
In a future user story it should be possible to keep the cards in their place in the list. For now, the edited card switches its place to the top of the cards list.

2022-10-24 19:45 UTC, kai-franke reviewed
Dear Gesa!
I have reviewed your code carefully, but I am not sure I fully understand the interaction of all the components and the props, so I would appreciate a second review. Sorry.

2022-10-24 19:45 UTC, kai-franke commented on components/EditCardForm/index.js
> +import React from "react";
I think you don't need to import `React` in this page.

2022-10-24 19:45 UTC, kai-franke commented on pages/index.js
> +  console.log(editEntryId);
Please remove `console.log`

2022-10-24 19:45 UTC, kai-franke commented on components/Cards/index.js
>  import React from "react";
I guess this import declaration is not needed.

2022-10-24 19:45 UTC, kai-franke commented on pages/index.js
>      <div>
Does this have to be a `<div>`? I guess it'll be visible in DOM. Maybe you can replace it with a fragment `<>  </>` ?

2022-10-24 19:45 UTC, kai-franke commented on pages/index.js
>  import { useState } from "react";
You could include this import in line 13:
```
import { useEffect, useState } from "react";
```

2022-10-25 07:14 UTC, CathrinTruchan commented on components/Card/index.js
> +      <button type="button" onClick={() => setEditEntryId(id)}>
Do you need the type=button?

2022-10-25 07:23 UTC, gacsphere commented on components/Card/index.js
>        </SecondaryInfo>
Hi Kai, this is the location data of the nesting box. If a scientist (as user) wants to draw the exact area of the data collection, he can do this by saving the location data. 
On some phones location data is disabled (because of big brother), so you have to enable it first. For that I will provide an info-message in another user story.

2022-10-25 07:24 UTC, gacsphere commented on components/Card/index.js
> +      <button type="button" onClick={() => setEditEntryId(id)}>
I'm not really sure. The default behavior of a button is "submit", that's why I wrote `type="button"` to make sure, that it's not a submit button.

2022-10-25 07:56 UTC, CathrinTruchan commented on components/Card/index.js
> +      <button type="button" onClick={() => setEditEntryId(id)}>
Yes, that's true, when the button is in a form. When it's not in a form I think it doesn't matter. But it's not a problem and propably also good for semantic reasons?

2022-10-25 08:29 UTC, gacsphere commented on components/Card/index.js
> +      <button type="button" onClick={() => setEditEntryId(id)}>
Ah, thank you Cathrin!

2022-10-26 10:38 UTC, AHen-C0de requested changes

2022-10-26 10:38 UTC, AHen-C0de commented on components/Cards/index.js
> +        if (nestingbox.id === showEditCard) {
The naming of your state `showEditCard` is confusing because I would read it as a Boolean like this. Maybe you could specify the name into something like `toEditCardID` because the id is what is saved in this state

2022-10-26 10:38 UTC, AHen-C0de commented on components/Cards/index.js
> +        } else {
In situations where it becomes hard to understand code, because it's complex and separated across files, I prefer it to use a bit more code than necessary to make it more readable for the future me, who has forgotten how the code works. Since your logic is, that the Card is displayed, as long as there is a null in `showEditCard`, you could write it like that:
`} else (showEditCard === null) { ... }`

This might also prevent future bugs, lets say, when another value than `id` or `null` enters your state.

2022-10-26 10:38 UTC, AHen-C0de commented on components/EditCardForm/index.js
> +        Date
It's english :D
It's a German website, right?

2022-10-26 10:38 UTC, AHen-C0de commented on components/EditCardForm/index.js
> +      <label htmlFor="time">Time</label>
English again xD

2022-10-26 10:45 UTC, AHen-C0de approved these changes

2022-10-26 12:41 UTC, gacsphere commented on components/Cards/index.js
> +        } else {
Thank you Angela for your input! Each time I read your comments I'm heavily impressed by your knowledge and your eagle eye! :)
This is the only one I'm not sure with yet because the result is different from my original result. Before, I had the card list displayed + the clicked card as edit form. With this change I wouldn't have the card list displayed anymore. There would only be left the editCardForm. At the moment that looks kind of strange because on top of the page I have a form displayed, which looks the same. This looks confusing. I have to think about this. In each case I have to change something in the appearance and I will keep this in mind to potentially implement it later. Thanks a lot!!!

2022-10-26 14:54 UTC, gacsphere commented on components/Cards/index.js
> +        } else {
Nevertheless it made me think about it and I might come back to this later. :)

2022-10-27 10:24 UTC, gacsphere commented
The code has been reviewed two times but didn't pass QA because of another problem in the form on top of the page (not the editCardForm, which was developed in this user story). So I made some additional changes mainly to the form and will go on with it in another user story, when I improve the UX for the forms.

The following has changed since the last code review: 
I set the preloaded values in the form from defaultValue to value and I don't show a default value anymore. This should lead the user to load the data with the new button "Lokale Daten laden" and the new function for this action "setLocalDataValues", which reloads the actual local data.
Now the local data can't be edited in the form anymore. I will work on the styling for that UX topic in another user story. But the local data can be edited in the editCardForm.

2022-10-27 12:46 UTC, sebsch1337 requested changes
Looks nice! Just some little recommendations :)

2022-10-27 12:46 UTC, sebsch1337 commented on pages/index.js
> +    setTime(resetedTime);
You could reduce the 2 lines to 1 line like setDate(new Date().toISOString().slice(0, 10));

2022-10-27 12:46 UTC, sebsch1337 commented on components/Cards.js
> +              count={nestingbox.count}
You could make it shorter when you only drill the full nestingbox object prop.

2022-10-27 12:46 UTC, sebsch1337 commented on components/EditCardForm.js
> +  count,
Here you could change it to accept only { nestingbox } . you can use them like
`defaultValue={nestingbox.date}`

2022-10-27 12:46 UTC, sebsch1337 commented on components/Form.js
> +        <label htmlFor="time">Zeit</label>
I would recommend to keep the app in english, since we communicate english in this course.

2022-10-27 12:46 UTC, sebsch1337 commented on components/Form.js
> +          Lokale Daten laden
The aria label is for english speaking people, the innerText is in german. Same here, i would recommend to stay in english.
Next has a localization service, where you can switch languages based on their location. I guess you already know how to determine users location ;)

2022-10-27 12:46 UTC, sebsch1337 commented on pages/index.js
> +    date: "2021-08-31",
I would recommend to use timestamps as dates. A timestamp is the time in seconds since 1.1.1970. You can easily calculate with it, since there are many date functions in JS.

2022-10-27 12:46 UTC, sebsch1337 commented on pages/index.js
> +    setDate(resetedDate);
Same here, you might reduce it to one line, since you don't need the variable resetedDate in a later stage.

2022-10-27 14:04 UTC, sebsch1337 approved these changes
LGTM! :)

2022-10-31 14:00 UTC, anhthu253 commented on components/Cards.js
> +            <EditCardForm
the component EditCardForm is actually quite the same as the component Form right?, with 3 more button. I would reuse the Form component and put all the buttons there. Depend on where u call the form, u can set the visibilty of these buttons true or false

2022-10-31 14:28 UTC, gacsphere commented on components/Cards.js
> +            <EditCardForm
Not exactly, they have different structure they work differently and later the will look differently. Now they only seem to be the same because they look alike. I have also thought about this yet, if I should make it only one component. But I doubt it will make sense later on that's why I would leave this for now as it is and maybe change it later into one component if it still makes sense.

2022-10-31 19:13 UTC, gacsphere commented on components/Cards.js
> +            <EditCardForm
They are not exactly the same. I also wondered if I could make them one component. Actually they look the same, but their styling may vary in the future (I could use conditional styling for that. I've implemented some now, and it work so far, but:). The submit-buttons have different functions and the inputs have different values and defaultValues. This may be the greatest difference. I think you cannot have both (value and defaultValue) for an input, when you want to keep it editable. And if I would make it one component I would need that.

2022-10-31 20:29 UTC, anhthu253 approved these changes

2022-11-02 08:30 UTC, sebsch1337 approved these changes
Looks good :) Just a little recommendation to have it shorter.

2022-11-02 08:30 UTC, sebsch1337 commented on components/EditCardForm.js
> +          }
You could shorten the validation, to avoid nesting ifs, so it will be easier to understand. Example:
`if (boxnumber.trim().length > 0) {
return setValidationLatitudeAlert("This is not a valid value for latitude. If you don't have a valid value, you can restore the value or leave the field empty.");
}`
The function will end when you return something. So you could first do the validations and then the logic to save / edit / delete.

2022-11-02 09:29 UTC, gacsphere commented on components/EditCardForm.js
> +          }
Thank you Sebastian! Yes, with the many validations it will be clearer the way you describe it. For that, I will write a new user story now! ;-)

2022-11-02 10:35 UTC, merged